In [1]:
import numpy as np
import pandas as pd

# NumPy

Task 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2
столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите
среднее значение по каждому признаку, используя метод mean массива Numpy. Результат
запишите в массив mean_a, в нем должно быть 2 элемента.

In [2]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

mean_a = np.array([[np.mean(a[:, 0]), np.mean(a[:, 1])]])

In [5]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [7]:
a.shape

(5, 2)

In [8]:
mean_a

array([[2. , 8.4]])

Task 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения
соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно
производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [10]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Task 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна
получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число
наблюдений.

In [14]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp / (a.shape[0] - 1)

2.0

Task 4
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с
помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать
транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером
2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом
1.

In [13]:
b = np.cov(a.T)
b[0,1]

2.0

# Pandas

Task 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со
столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и
['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно
содержатся данные:
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и
поклонники']

In [16]:
d_authors = {
    'author_id': [1, 2, 3],
    'author_name': ['Тургенев', 'Чехов', 'Островский']
}

df_authors = pd.DataFrame(d_authors)

d_books = {
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза',
                   'Таланты и поклонники'],
    'price': [500, 400, 350, 450, 600, 725, 425]
}

df_books = pd.DataFrame(d_books)

In [17]:
df_authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [18]:
df_books

author_id            book_title  price
0          1           Отцы и дети    500
1          1                 Рудин    400
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    450
4          2       Дама с собачкой    600
5          3                 Гроза    725
6          3  Таланты и поклонники    425

Task 2 Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id

In [20]:
df_authors_price = df_authors.merge(df_books, on='author_id')
df_authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    500
1          1    Тургенев                 Рудин    400
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    450
4          2       Чехов       Дама с собачкой    600
5          3  Островский                 Гроза    725
6          3  Островский  Таланты и поклонники    425

Task 3 Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими
книгами.

In [32]:
df_top5 = df_authors_price.sort_values('price', ascending=False)
df_top5.reset_index().drop(columns={'index'}).iloc[:5]

author_id author_name            book_title  price
0          3  Островский                 Гроза    725
1          2       Чехов       Дама с собачкой    600
2          1    Тургенев           Отцы и дети    500
3          2       Чехов      Толстый и тонкий    450
4          3  Островский  Таланты и поклонники    425

Task 4 Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat
должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя
цена на книги этого автора.

In [88]:
grouped = df_authors_price.groupby('author_name')
df_authors_stat = grouped.agg(min=('price', 'min'),
                           max=('price','max'),
                           mean=('price','mean'))
df_authors_stat.reset_index(inplace=True)
df_authors_stat

author_name  min  max        mean
0  Островский  425  725  575.000000
1    Тургенев  350  500  416.666667
2       Чехов  450  600  525.000000

Task 5 Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться
данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные
из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot table с помощью вопросительного знака.Для каждого
автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого
функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами
должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при
необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием
"book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь,
что датафреймы book_info и book_info2 идентичны.

In [89]:
df_authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [95]:
df_book_info_pvt = df_authors_price.pivot_table(index='author_name', columns='cover', values='price', aggfunc='sum', fill_value=0)

In [96]:
df_book_info_pvt

cover        мягкая  твердая
author_name                 
Островский     1150        0
Тургенев        750      500
Чехов             0     1050

In [102]:
df_book_info_groupby = df_authors_price.groupby(['author_name','cover']).agg({'price':'sum'}).unstack('cover').fillna(0)

In [103]:
df_book_info_groupby

price        
cover        мягкая твердая
author_name                
Островский   1150.0     0.0
Тургенев      750.0   500.0
Чехов           0.0  1050.0

In [122]:
df_book_info_pvt.to_pickle('book_info.pkl')
df_pkl = pd.read_pickle('book_info.pkl')
df_pkl

cover        мягкая  твердая
author_name                 
Островский     1150        0
Тургенев        750      500
Чехов             0     1050

In [123]:
df_book_info_pvt.to_csv('book_info.csv', sep=',')
df_csv = pd.read_csv('book_info.csv')
df_csv

author_name  мягкая  твердая
0  Островский    1150        0
1    Тургенев     750      500
2       Чехов       0     1050